### ISSUE TITLE
"t411.io" to "t411.in" in t411downloader.js 

### ISSUE THREAD

**Issue by Yotakana** [lmanul/t411downloader#1]
you also have to change the url line 13 in "t411downloader.js"

this one :

    url: 'http://*.t411.io/*'}, this.onTabsAvailable.bind(this));

for the new one :

    url: 'http://*.t411.in/*'}, this.onTabsAvailable.bind(this));

**Comment by lmanul** [comment]
Thanks a lot! Fixed :-)
